/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab9;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.*;

/**
 *
 * @author denni
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    ArrayList<Contacto> listContacto = new ArrayList();
    ArrayList<Mensaje> listMensaje = new ArrayList();
    ArrayList<Thread> listLlamada = new ArrayList();
    SaveData SD = new SaveData();
    int gI = 0;

    public Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JD1_TF_Nombre = new javax.swing.JTextField();
        JD1_SP_Edad = new javax.swing.JSpinner();
        JD1_TF_Correo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JD1_TF_Numero = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JD1_TA_Direccion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        JD1_RB_M = new javax.swing.JRadioButton();
        JD1_RB_F = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        JD1_CB_Contactos = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        OKBUTTON = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jDialog3 = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        JD3_JL_Contactos = new javax.swing.JList<>();
        jButton8 = new javax.swing.JButton();
        jDialog4 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        JD4_TA_Mensaje = new javax.swing.JTextArea();
        JD4_CB_Contactos = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jDialog5 = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTree2 = new javax.swing.JTree();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        JD5_CB_Contactos = new javax.swing.JComboBox<>();
        jDialog6 = new javax.swing.JDialog();
        jScrollPane6 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        jLabel1.setText("Nombre");

        jLabel2.setText("Edad");

        jLabel3.setText("Numero");

        jLabel4.setText("Correo");

        JD1_TF_Correo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JD1_TF_CorreoActionPerformed(evt);
            }
        });

        jLabel5.setText("Direccion");

        JD1_TA_Direccion.setColumns(20);
        JD1_TA_Direccion.setRows(5);
        jScrollPane1.setViewportView(JD1_TA_Direccion);

        jLabel6.setText("Genero");

        JD1_RB_M.setText("Hombre");

        JD1_RB_F.setText("Mujer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JD1_SP_Edad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JD1_TF_Numero, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(JD1_TF_Correo)
                            .addComponent(JD1_TF_Nombre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(JD1_RB_M, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(JD1_RB_F)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JD1_TF_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JD1_SP_Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JD1_TF_Numero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JD1_TF_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(JD1_RB_M)
                    .addComponent(JD1_RB_F))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(32, 32, 32))
        );

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        JD1_CB_Contactos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JD1_CB_Contactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JD1_CB_ContactosMouseClicked(evt);
            }
        });
        JD1_CB_Contactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JD1_CB_ContactosActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        OKBUTTON.setText("Modificar");
        OKBUTTON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKBUTTONActionPerformed(evt);
            }
        });

        jLabel9.setText("* Clickear la barra ");

        jLabel10.setText("para obtener Datos");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JD1_CB_Contactos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(OKBUTTON, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(OKBUTTON)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JD1_CB_Contactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jTree1);

        jButton3.setText("Clasificar por Edad");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Clasificar por Genero");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 245, Short.MAX_VALUE)
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog2Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        JD3_JL_Contactos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(JD3_JL_Contactos);

        jButton8.setText("Llamar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel11.setText("Mensaje");

        JD4_TA_Mensaje.setColumns(20);
        JD4_TA_Mensaje.setRows(5);
        jScrollPane3.setViewportView(JD4_TA_Mensaje);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JD4_CB_Contactos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Elegir Receptor");

        jButton5.setText("Enviar Mensaje");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jDialog4Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5))
                    .addComponent(JD4_CB_Contactos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog4Layout.createSequentialGroup()
                .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JD4_CB_Contactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jScrollPane4.setViewportView(jTree2);

        jButton6.setText("Clasificar por Fecha");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Clasificar por Persona");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        JD5_CB_Contactos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jDialog5Layout = new javax.swing.GroupLayout(jDialog5.getContentPane());
        jDialog5.getContentPane().setLayout(jDialog5Layout);
        jDialog5Layout.setHorizontalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JD5_CB_Contactos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jDialog5Layout.setVerticalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog5Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JD5_CB_Contactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(Tabla);

        javax.swing.GroupLayout jDialog6Layout = new javax.swing.GroupLayout(jDialog6.getContentPane());
        jDialog6.getContentPane().setLayout(jDialog6Layout);
        jDialog6Layout.setHorizontalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 595, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog6Layout.setVerticalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText(" ^        ᴥ        ^");

        jMenu1.setText("Contactos");

        jMenuItem1.setText("Manejar Contactos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Listar Contactos");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText("Registro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText("Hacer Llamada");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu3.setText("Mensajes");

        jMenuItem7.setText("Crear Mensaje");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Buzon");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenu1.add(jMenu3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("File");

        jMenuItem5.setText("Save");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Load");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        JD1_CB_Contactos.removeAllItems();
        for (int i = 0; i < listContacto.size(); i++) {
            JD1_CB_Contactos.addItem(listContacto.get(i).getNombre());
        }
        jDialog1.pack();
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Contactos");
        for (int i = 0; i < listContacto.size(); i++) {
            DefaultMutableTreeNode cont = new DefaultMutableTreeNode(listContacto.get(i));
            DefaultMutableTreeNode nd1 = new DefaultMutableTreeNode(listContacto.get(i).Numero);
            DefaultMutableTreeNode nd2 = new DefaultMutableTreeNode(listContacto.get(i).Direccion);
            DefaultMutableTreeNode nd3 = new DefaultMutableTreeNode(listContacto.get(i).Correo);
            DefaultMutableTreeNode nd4 = new DefaultMutableTreeNode(listContacto.get(i).Edad);
            DefaultMutableTreeNode nd5 = new DefaultMutableTreeNode(listContacto.get(i).Genero);
            DefaultMutableTreeNode nd6 = new DefaultMutableTreeNode(listContacto.get(i).Nombre);
            cont.add(nd6);
            cont.add(nd1);
            cont.add(nd2);
            cont.add(nd3);
            cont.add(nd4);
            cont.add(nd5);
            root.add(cont);
        }
        DefaultTreeModel model = new DefaultTreeModel(root);
        jTree1.setModel(model);
        jDialog2.pack();
        jDialog2.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void JD1_TF_CorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JD1_TF_CorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JD1_TF_CorreoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Contacto c = CrearContacto(0);
        listContacto.add(c);
        JD1_TF_Nombre.setText("");
        JD1_TF_Numero.setText("");
        JD1_SP_Edad.setValue(0);
        JD1_TF_Correo.setText("");
        JOptionPane.showConfirmDialog(this, "Contacto excitosamente agregado!");
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = JD1_CB_Contactos.getSelectedIndex();
        listContacto.remove(i);
        JOptionPane.showConfirmDialog(this, "Contacto excitosamente eliminado!");
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void OKBUTTONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKBUTTONActionPerformed
        Contacto c = CrearContacto(0);
        listContacto.set(JD1_CB_Contactos.getSelectedIndex(), c);
    }//GEN-LAST:event_OKBUTTONActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        SD.SaveBinario(listContacto);
        SD.SaveMensaje(listMensaje);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        listContacto = SD.LoadBinario();
        listMensaje = SD.LoadMensaje();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        JD4_CB_Contactos.removeAllItems();
        for (int i = 0; i < listContacto.size(); i++) {
            JD4_CB_Contactos.addItem(listContacto.get(i).Nombre);
        }
        jDialog4.pack();
        jDialog4.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        DefaultListModel model = new DefaultListModel();
        for (int i = 0; i < listContacto.size(); i++) {
            model.addElement(listContacto.get(i));
        }
        JD3_JL_Contactos.setModel(model);
        jDialog3.pack();
        jDialog3.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ArrayList<Contacto> list = listContacto;
        Collections.sort(list,
                new Comparator<Contacto>() {
            public int compare(Contacto s1, Contacto s2) {
                return s1.Edad - s2.Edad;
            }
        });
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Contactos");
        for (int i = 0; i < list.size(); i++) {
            DefaultMutableTreeNode cont = new DefaultMutableTreeNode(list.get(i));
            DefaultMutableTreeNode nd1 = new DefaultMutableTreeNode(list.get(i).Numero);
            DefaultMutableTreeNode nd2 = new DefaultMutableTreeNode(list.get(i).Direccion);
            DefaultMutableTreeNode nd3 = new DefaultMutableTreeNode(list.get(i).Correo);
            DefaultMutableTreeNode nd4 = new DefaultMutableTreeNode(list.get(i).Edad);
            DefaultMutableTreeNode nd5 = new DefaultMutableTreeNode(list.get(i).Genero);
            DefaultMutableTreeNode nd6 = new DefaultMutableTreeNode(list.get(i).Nombre);
            cont.add(nd6);
            cont.add(nd1);
            cont.add(nd2);
            cont.add(nd3);
            cont.add(nd4);
            cont.add(nd5);
            root.add(cont);
        }
        DefaultTreeModel model = new DefaultTreeModel(root);
        jTree1.setModel(model);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Contactos");
        ArrayList<Contacto> list = new ArrayList();
        for (int i = 0; i < listContacto.size(); i++) {
            if (listContacto.get(i).Genero.equals("Hombre")) {
                list.add(listContacto.get(i));
            }
        }
        for (int i = 0; i < listContacto.size(); i++) {
            if (listContacto.get(i).Genero.equals("Mujer")) {
                list.add(listContacto.get(i));
            }
        }
        for (int i = 0; i < listContacto.size(); i++) {
            if (listContacto.get(i).Genero.equals("?")) {
                list.add(listContacto.get(i));
            }
        }
        for (int i = 0; i < list.size(); i++) {
            DefaultMutableTreeNode cont = new DefaultMutableTreeNode(list.get(i));
            DefaultMutableTreeNode nd1 = new DefaultMutableTreeNode(list.get(i).Numero);
            DefaultMutableTreeNode nd2 = new DefaultMutableTreeNode(list.get(i).Direccion);
            DefaultMutableTreeNode nd3 = new DefaultMutableTreeNode(list.get(i).Correo);
            DefaultMutableTreeNode nd4 = new DefaultMutableTreeNode(list.get(i).Edad);
            DefaultMutableTreeNode nd5 = new DefaultMutableTreeNode(list.get(i).Genero);
            DefaultMutableTreeNode nd6 = new DefaultMutableTreeNode(list.get(i).Nombre);
            cont.add(nd6);
            cont.add(nd1);
            cont.add(nd2);
            cont.add(nd3);
            cont.add(nd4);
            cont.add(nd5);
            root.add(cont);
        }
        DefaultTreeModel model = new DefaultTreeModel(root);
        jTree1.setModel(model);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Mensaje m = CrearMensaje(0);
        listMensaje.add(m);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        JD5_CB_Contactos.removeAllItems();
        for (int i = 0; i < listContacto.size(); i++) {
            JD5_CB_Contactos.addItem(listContacto.get(i).getNombre());
        }
        jDialog5.pack();
        jDialog5.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        ArrayList<Mensaje> list = listMensaje;
        Collections.sort(list,
                new Comparator<Mensaje>() {
            public int compare(Mensaje s1, Mensaje s2) {
                return s1.getFecha().compareTo(s2.getFecha());
            }
        });
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Contactos");
        for (int i = 0; i < list.size(); i++) {
            DefaultMutableTreeNode cont = new DefaultMutableTreeNode(list.get(i));
            DefaultMutableTreeNode nd1 = new DefaultMutableTreeNode("Emisor: " + list.get(i).Emisor);
            DefaultMutableTreeNode nd2 = new DefaultMutableTreeNode("Receptor: " + list.get(i).Receptor);
            DefaultMutableTreeNode nd3 = new DefaultMutableTreeNode("Fecha: " + list.get(i).Fecha);
            DefaultMutableTreeNode nd4 = new DefaultMutableTreeNode(list.get(i).Contenido);
            cont.add(nd1);
            cont.add(nd2);
            cont.add(nd3);
            cont.add(nd4);
            root.add(cont);
        }
        DefaultTreeModel model = new DefaultTreeModel(root);
        jTree2.setModel(model);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        ArrayList<Mensaje> list = listMensaje;
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Contactos");
        for (int i = 0; i < list.size(); i++) {
            String s1 = list.get(i).Receptor;
            String s2 = listContacto.get(JD5_CB_Contactos.getSelectedIndex()).Nombre;
            if (s1.equals(s2)) {
                DefaultMutableTreeNode cont = new DefaultMutableTreeNode(list.get(i));
                DefaultMutableTreeNode nd1 = new DefaultMutableTreeNode(list.get(i).Emisor);
                DefaultMutableTreeNode nd2 = new DefaultMutableTreeNode(list.get(i).Receptor);
                DefaultMutableTreeNode nd3 = new DefaultMutableTreeNode(list.get(i).Fecha);
                DefaultMutableTreeNode nd4 = new DefaultMutableTreeNode(list.get(i).Contenido);
                cont.add(nd1);
                cont.add(nd2);
                cont.add(nd3);
                cont.add(nd4);
                root.add(cont);
            }
        }
        DefaultTreeModel model = new DefaultTreeModel(root);
        jTree2.setModel(model);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void JD1_CB_ContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JD1_CB_ContactosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JD1_CB_ContactosActionPerformed

    private void JD1_CB_ContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JD1_CB_ContactosMouseClicked
        Contacto c = listContacto.get(JD1_CB_Contactos.getSelectedIndex());
        JD1_TF_Nombre.setText(c.getNombre());
        JD1_TF_Numero.setText(c.getNumero() + "");
        JD1_SP_Edad.setValue(c.getEdad());
        JD1_TF_Correo.setText(c.getCorreo());
        JD1_TA_Direccion.setText(c.getDireccion());
    }//GEN-LAST:event_JD1_CB_ContactosMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Llamada c = new Llamada();
        c.Emisor = "Yo";
        c.Receptor = listContacto.get(JD3_JL_Contactos.getSelectedIndex()).Nombre;
        listLlamada.add(new Thread(c));
        listLlamada.get(gI).start();
        gI++;
        c.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Tiempo");
        model.addColumn("Colgado");
        model.addColumn("Emisor");
        model.addColumn("Receptor");
        model.addColumn("jButton1");
        model.addColumn("jLabel1");
        model.addColumn("jLabel2");
        if (listLlamada.size() >= 0) {
            Object[] o = new Object[model.getColumnCount()];
            for (int i = 0; i < listLlamada.size(); i++) {

                model.addRow(o);
            }
        }
        Tabla.setModel(model);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    public Contacto CrearContacto(int Serie) {
        String Nombre = JD1_TF_Nombre.getText();
        int Edad = (int) JD1_SP_Edad.getValue();
        int Numero = Integer.parseInt(JD1_TF_Numero.getText());
        String Correo = JD1_TF_Correo.getText();
        String Direccion = JD1_TA_Direccion.getText();
        String Genero;
        if (JD1_RB_M.isSelected()) {
            Genero = "Hombre";
        } else if (JD1_RB_F.isSelected()) {
            Genero = "Mujer";
        } else {
            Genero = "?";
        }
        Contacto c = new Contacto(Nombre, Edad, Numero, Correo, Direccion, Genero);
        return c;
    }

    public void actualizar() {
        JD1_CB_Contactos.removeAllItems();
        for (int i = 0; i < listContacto.size(); i++) {
            JD1_CB_Contactos.addItem(listContacto.get(i).getNombre());
        }
    }

    public Mensaje CrearMensaje(int Serie) {
        String Emisor = "Usuario";
        String Receptor = listContacto.get(JD4_CB_Contactos.getSelectedIndex()).getNombre();
        Date Fecha = new Date();
        String Contenido = JD4_TA_Mensaje.getText();
        Mensaje c = new Mensaje(Emisor, Receptor, Fecha, Contenido);
        return c;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JD1_CB_Contactos;
    private javax.swing.JRadioButton JD1_RB_F;
    private javax.swing.JRadioButton JD1_RB_M;
    private javax.swing.JSpinner JD1_SP_Edad;
    private javax.swing.JTextArea JD1_TA_Direccion;
    private javax.swing.JTextField JD1_TF_Correo;
    private javax.swing.JTextField JD1_TF_Nombre;
    private javax.swing.JTextField JD1_TF_Numero;
    private javax.swing.JList<String> JD3_JL_Contactos;
    private javax.swing.JComboBox<String> JD4_CB_Contactos;
    private javax.swing.JTextArea JD4_TA_Mensaje;
    private javax.swing.JComboBox<String> JD5_CB_Contactos;
    private javax.swing.JButton OKBUTTON;
    private javax.swing.JTable Tabla;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTree jTree1;
    private javax.swing.JTree jTree2;
    // End of variables declaration//GEN-END:variables
}
